<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <RootNamespace>PlcMonitor.Web</RootNamespace>
    <AssemblyName>PlcMonitor.Web</AssemblyName>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PlcMonitor.Core\PlcMonitor.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
  <ProjectReference Include="..\PlcMonitor.Scanner\PlcMonitor.Scanner.csproj" />
</ItemGroup>

  <!-- Копируем net48-версию Newtonsoft.Json для Scanner.exe subprocess -->
<Target Name="CopyScannerToSubdir" AfterTargets="Build">
  <MakeDir Directories="$(OutputPath)Scanner" />
  <ItemGroup>
    <ScannerFiles Include="$(MSBuildThisFileDirectory)..\PlcMonitor.Scanner\bin\x64\Debug\net48\*.*" />
  </ItemGroup>
  <Copy
    SourceFiles="@(ScannerFiles)"
    DestinationFolder="$(OutputPath)Scanner"
    OverwriteReadOnlyFiles="true"
    SkipUnchangedFiles="false" />
</Target>

</Project>