<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <RootNamespace>PlcMonitor.Web</RootNamespace>
    <AssemblyName>PlcMonitor.Web</AssemblyName>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PlcMonitor.Core\PlcMonitor.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
  <ProjectReference Include="..\PlcMonitor.Scanner\PlcMonitor.Scanner.csproj" />
</ItemGroup>

</Project>